name: ⭐ Feature Request
description: Share your ideas to improve De1984
title: "Feature Request: "
labels: enhancement

body:
  - type: textarea
    id: describe
    attributes:
      label: Describe Your Idea
      description: What feature or improvement would you like to see in De1984?
      placeholder: |
        Example: Add ability to export firewall rules to a file
        
        Please be as specific as possible about:
        - What you want to achieve
        - Why this feature would be useful
        - How you envision it working
    validations:
      required: true
